# Descarrega una imatge base amb Apache + PHP 8.3
FROM php:8.3-apache

# Directori de treball dins el contenidor
WORKDIR /var/www/html

# Copia l'aplicació
COPY app .

# Exposa el port 80/tcp dins el contenidor
EXPOSE 80

